name: ci

on: [push, pull_request]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: deno run -A https://deno.land/x/deploy/deployctl.ts deploy --project=pkg --import-map=./import_map.json main.ts
